# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Tests

on:
  push:
    branches: [ devel, prefixes-update ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 3

    strategy:
      matrix:
        node-version: [12.x, 14.x, 15.x, 16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    # https://github.com/actions/cache/blob/main/examples.md#using-multiple-systems-and-npm-config
    - name: Get npm cache directory
      id: npm-cache
      run: |
        echo "::set-output name=dir::$(npm config get cache)"
    - name: npm cache
      uses: actions/cache@v2
      with:
        path: ${{ steps.npm-cache.outputs.dir }}
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Install dependencies
      run: npm ci

    - name: Run tests (with node-sass support)
      run: |
        time npm install node-sass@5.0.0
        npm test

    - name: Run bin/analyze-css.js for CSS file
      run: ./bin/analyze-css.js --file examples/ti.mobile.css  -p | jq .metrics

    - name: Run bin/analyze-css.js for SCSS file
      run: ./bin/analyze-css.js --file examples/base.scss  -p | jq .offenders

    - name: Run bin/analyze-css.js for stdin-provided CSS
      run: cat examples/ti.mobile.css | ./bin/analyze-css.js - | jq .metrics

    - name: Run bin/analyze-css.js for external file over HTTP
      run: ./bin/analyze-css.js --url http://s3.macbre.net/analyze-css/propertyResets.css -p | jq .metrics

    - name: Run bin/analyze-css.js for external file over HTTPS (--ignore-ssl-errors)
      run: ./bin/analyze-css.js --url https://s3.macbre.net/analyze-css/propertyResets.css --ignore-ssl-errors | jq .metrics
