name: CSS prefixes

# Controls when the action will run. 
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 5 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    env:
      GIT_BRANCH: "devel"
      GIT_USER_NAME: "macbre"
      GIT_USER_EMAIL: "<macbre@users.noreply.github.com>"

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # https://github.com/actions/checkout
      - name: Cloning ${{ env.GIT_BRANCH }} branch
        uses: actions/checkout@v2-beta
        with:
          ref: ${{ env.GIT_BRANCH }}

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 15.x

      - name: Update prefixes
        run: |
          npm ci
          npm run prefixes

      # https://github.com/actions/checkout#push-a-commit-using-the-built-in-token
      - name: Set up git
        run: |
          git config user.name ${GIT_USER_NAME}
          git config user.email ${GIT_USER_EMAIL}

      - name: Show a diff
        run: |
          git diff

      - name: Commit if needed to a new branch
        continue-on-error: true
        run: |
          export PR_BRANCH="prefixes-update"
          git checkout -b ${PR_BRANCH}
          git add .
          git commit -m 'Updating rules/prefixes.json' && git push origin ${PR_BRANCH} --force

      # https://github.com/marketplace/actions/github-pull-request-action#advanced-options
      - name: Create a pull request from the changes above
        uses: repo-sync/pull-request@v2
        if: ${{ success() }}
        with:
          source_branch: "prefixes-update"  # see above
          destination_branch: "devel"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_label: "dependencies"
          pr_assignee: "macbre"
